# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3202245ab56e6de86de12a66c25e076cf7ff71fe9197a88a3c2d8f3bdfc79d6a74f532c825b8ccb3a19b1b8f693093cacf72058a9595ad6ccf7e4462edfe4714

test:
  secret_key_base: 452d5d7dda73c636fdeabc70b729f3a5298ef260a418886203eda85be83747b6307f038b550c3fb1979e67a7d8d14a455fab3bd0bbcadccb685cf19d31da3b60

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
